version: '3'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=otus
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=auth_test
    ports:
      - 5432

  server:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    command: /server/server --addr 0.0.0.0:50052 --config-path configs/config.yaml
    volumes:
      - ../configs:/server/configs
    ports:
      - 50052:50052
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_test
      - DB_USER=otus
      - DB_PASSWORD=1234
      - DB_CONNECTION_RETRIES=20
      - DB_CONNECTION_TIMEOUT=10
      - RUST_LOG=info
    depends_on:
      - db

  tests:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile-tests
    volumes:
      - ../configs:/server/configs
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_test
      - DB_USER=otus
      - DB_PASSWORD=1234
      - DB_CONNECTION_RETRIES=20
      - DB_CONNECTION_TIMEOUT=10
      - API_SERVER_URL=http://server:50052
      - API_CONNECTION_RETRIES=20
      - API_CONNECTION_TIMEOUT=10
      - RUST_LOG=info
    depends_on:
      - db
      - server
