# limits are max attempts per minute for each login/password/ip
limits:
  login: 10
  password: 100
  ip: 1000

timeouts:
  # how long in seconds rate limit bucket must not be touched until marked as inactive
  bucket_active_secs: 180

# logger:
#   level: "debug"
#   output_paths:
#     - stderr
#     - /tmp/antibruteforce/outlog
#   error_output_paths:
#     - stderr
#     - /tmp/antibruteforce/errlog