# limits are max attempts per minute for each login/password/ip
limits:
  login: 10
  password: 100
  ip: 1000

timeouts:
  # how long in seconds rate limit bucket must not be touched until marked as inactive
  bucket_active_secs: 180

  # how long in seconds access token is valid after creation
  access_token_expiration_secs: 300 # 5 minutes

  # how long in seconds refresh token is valid after creation
  refresh_token_expiration_secs: 86400  # 24 hours