name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup protobuf
      run: https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip \
            && unzip protoc-27.1-linux-x86_64.zip -d /tmp \
            && export PATH="$PATH:/tmp/bin"

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --lib --verbose
