name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup protobuf
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip
        unzip protoc-27.1-linux-x86_64.zip -d /tmp
        mv /tmp/bin/protoc /usr/bin/protoc

    - name: Fmt check
      run: cargo fmt --check

    - name: Lint check
      run: cargo clippy

    - name: Run tests
      run: cargo test --lib --verbose
